<body style="background-color: #fdccbc;">
    <section class="vh-100">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col">
            <p><span class="h2">Order Cart </span></p>
    
            <?php
            echo $order;
            ?>
    
            <div class="card mb-5">
              <div class="card-body p-4">
    
                <div class="float-end">
                  <p class="mb-0 me-5 d-flex align-items-center">
                    <span class="small text-muted me-2">Order total:</span> <span
                      class="lead fw-normal">$<?php echo $total ?></span>
                  </p>
                </div>
    
              </div>
            </div>
    
            <div class="d-flex justify-content-end">
              <a href="/product" class="btn btn-warning btn-lg me-2">Continue shopping</a>
            </div>
    
          </div>
        </div>
      </div>
    </section>
</body>